spring:
  profiles:
    include:
      - db
      - jwt
<<<<<<< HEAD
  security:
    user:
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
=======
      - oauth
>>>>>>> 4fb49f6fceb6d07f5daa82cb3a324ab6285dd45d
