spring:
  profiles:
    include:
      - db
      - jwt
      - path
      - cloudinary
      - oauth
      - openbank
  security:
    user:
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher